services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "5432:5432"

volumes:
  postgresql_data: