services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../customer:/data
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "5432:5432"
    networks:
      - piscineds_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    environment :
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - piscineds_network
    depends_on :
      - postgres

volumes:
  postgresql_data:
  pgadmin_data:

networks:
  piscineds_network: